const dummyAssocNetwork = {
  Alex: ["Entity1", "Entity2"],
  Entity1: ["Alex", "Richard", "John", "Sylvian", "Mahmood"],
  Entity2: ["Alex", "Saleem", "Meherbano", "John"],
  Richard: ["Entity1", "Entity3", "Entity4"],
  John: ["Entity1", "Entity5", "Entity6", "Entity7", "Entity2"],
  Sylvian: ["Entity1", "Entity8"],
  Mahmood: ["Entity1"],
  Entity3: ["Richard"],
  Entity4: ["Richard"],
  Entity5: ["John"],
  Entity6: ["John", "Junaid"],
  Entity7: ["John", "Omar", "Saad", "Hasan", "Faheem"],
  Junaid: ["Entity6", "Entity8"],
  Omar: ["Entity7"],
  Saad: ["Entity7"],
  Hasan: ["Entity7"],
  Entity8: ["Sylvian", "Junaid", "Danial", "Nadeem"],
  Danial: ["Entity8"],
  Nadeem: ["Entity8"],
  Saleem: ["Entity2", "Entity9", "Entity10", "Entity11"],
  Meherbano: ["Entity2", "Entity12"],
  Entity9: ["Saleem"],
  Entity10: ["Saleem", "Faheem"],
  Entity11: ["Saleem"],
  Faheem: ["Entity10", "Entity7"],
  Entity12: ["Meherbano", "Shah"],
  Shah: ["Entity12", "Entity13"],
  Entity13: ["Shah"],
};

export { dummyAssocNetwork };
